import { ActionEnum, ModeEnum, MultiActionEnum, Strategy } from '@concordia-nx-ionic/concordia-shared';

export const peruContractsDataConfig: Strategy = {
  name: 'contracts',
  entity: 'meterContract',
  column: 3,
  columns: [
    {
      field: 'meterContractId',
      contentType: 'hidden',
      rowSelector: 'meterContractId',
      rowEditSelector: 'meterContractId',
      required: true,
      searchType: 'hidden',
      searchSelector: 'meterContractId',
      editType: 'hidden',
      filterType: 'array',
      options: [],
      hidden: [ModeEnum.LIST_EDIT, ModeEnum.LIST_VIEW],
    },
    {
      field: '_id',
      contentType: 'hidden',
      rowSelector: '_id',
      rowEditSelector: '_id',
      required: true,
      searchType: 'hidden',
      searchSelector: '_id',
      editType: 'hidden',
      filterType: 'array',
      options: [],
      hidden: [ModeEnum.LIST_EDIT, ModeEnum.LIST_VIEW],
    },
    {
      field: 'department',
      contentType: 'string',
      rowSelector: 'department.name',
      rowEditSelector: 'departmentId',
      required: true,
      searchType: 'multiSelectSearch',
      searchSelector: 'departmentId',
      editType: 'selectSearch',
      filterType: 'array',
      options: [],
      optionsValue: 'departmentId',
    },
    {
      field: 'zoneId',
      contentType: 'string',
      rowSelector: 'zoneId',
      rowEditSelector: 'zoneId',
      required: true,
      searchType: 'multiSelectSearch',
      searchSelector: 'zoneId',
      editType: 'selectSearch',
      filterType: 'array',
      options: [],
      optionsValue: 'zoneId',
    },
    {
      field: 'tariff',
      contentType: 'string',
      rowSelector: 'tariff',
      rowEditSelector: 'tariff',
      required: true,
      searchType: 'multiSelectSearch',
      searchSelector: 'tariff',
      editType: 'selectSearch',
      filterType: 'array',
      options: [],
      optionsValue: 'tariffId',
    },

    {
      field: 'regulation',
      contentType: 'string',
      rowSelector: 'regulation',
      rowEditSelector: 'regulation',
      required: true,
      searchType: 'hidden',
      editType: 'text',
      searchSelector: 'regulation',
      filterType: 'string',
      options: [],
      hidden: [ModeEnum.LIST_EDIT, ModeEnum.LIST_VIEW],
    },
    {
      field: 'tags',
      contentType: 'string',
      rowSelector: 'tags',
      rowEditSelector: 'tags',
      required: true,
      searchType: 'hidden',
      editType: 'text',
      searchSelector: 'tags',
      filterType: 'string',
      options: [],
      hidden: [ModeEnum.LIST_EDIT, ModeEnum.LIST_VIEW],
    },
    {
      field: 'appliesFrom',
      contentType: 'date',
      rowSelector: 'fromDateUnixTs',
      rowEditSelector: 'fromDateUnixTs',
      required: true,
      hideSeconds: false,
      searchType: 'date',
      editType: 'date',
      filterType: 'string',
      filterRange: true,
      options: [],
      cssClass: 'w-auto',
    },
    {
      field: 'distributor',
      contentType: 'string',
      rowSelector: 'distributor.name',
      rowEditSelector: 'distributorId',
      required: true,
      searchType: 'multiSelectSearch',
      searchSelector: 'distributorId',
      editType: 'selectSearch',
      filterType: 'array',
      options: [],
      optionsValue: 'distributorId',
    },

    {
      field: 'power',
      contentType: 'number',
      rowSelector: 'power',
      rowEditSelector: 'power',
      required: true,
      searchType: 'number',
      searchSelector: 'power',
      filterType: 'double',
      options: [],
    },
    {
      field: 'voltage',
      contentType: 'number',
      rowSelector: 'voltage',
      rowEditSelector: 'voltage',
      required: true,
      searchType: 'number',
      editType: 'number',
      searchSelector: 'voltage',
      filterType: 'double',
      options: [],
    },
    {
      field: 'igv',
      contentType: 'number',
      rowSelector: 'igv',
      rowEditSelector: 'igv',
      required: true,
      searchType: 'number',
      editType: 'number',
      searchSelector: 'igv',
      filterType: 'double',
      options: [],
      min: 0,
      max: 100,
      step: 0.001,
      defaultValue: 18,
      hidden: [ModeEnum.LIST_EDIT, ModeEnum.LIST_VIEW],
    },
    {
      field: 'elecRural',
      contentType: 'number',
      rowSelector: 'elecRural',
      rowEditSelector: 'elecRural',
      required: true,
      searchType: 'number',
      editType: 'number',
      searchSelector: 'elecRural',
      filterType: 'double',
      min: 0,
      max: 1,
      step: 0.00001,
      defaultValue: 0.0088,
      options: [],
      hidden: [ModeEnum.LIST_EDIT, ModeEnum.LIST_VIEW],
    },
    {
      field: 'connectionType',
      contentType: 'string',
      rowSelector: 'connectionType.name',
      rowEditSelector: 'connectionTypeId',
      required: true,
      searchType: 'select',
      editType: 'select',
      searchSelector: 'connectionTypeId',
      filterType: 'array',
      options: [],
      optionsValue: 'connectionTypeId',
      hidden: [ModeEnum.LIST_EDIT, ModeEnum.LIST_VIEW],
    },
  ],
  actions: [
    { type: ActionEnum.EDIT },
    { type: ActionEnum.DELETE },
  ],
  multiActions: [
    {
      icon: 'trash-outline',
      name: 'delete',
      type: MultiActionEnum.DELETE,
    },
  ],
  editActions: [
    { type: ActionEnum.CANCEL },
    { type: ActionEnum.DELETE },
  ],
};
