import { ActionEnum, ModeEnum, MultiActionEnum, Strategy } from '@concordia-nx-ionic/concordia-shared';

export const spainContractsDataConfig: Strategy = {
  name: 'contracts',
  entity: 'meterContract',
  column: 3,
  columns: [
    {
      field: 'meterContractId',
      contentType: 'hidden',
      rowSelector: 'meterContractId',
      rowEditSelector: 'meterContractId',
      required: true,
      searchType: 'hidden',
      searchSelector: 'meterContractId',
      editType: 'hidden',
      filterType: 'array',
      options: [],
      hidden: [ModeEnum.LIST_EDIT, ModeEnum.LIST_VIEW],
    },
    {
      field: '_id',
      contentType: 'hidden',
      rowSelector: '_id',
      rowEditSelector: '_id',
      required: true,
      searchType: 'hidden',
      searchSelector: '_id',
      editType: 'hidden',
      filterType: 'array',
      options: [],
      hidden: [ModeEnum.LIST_EDIT, ModeEnum.LIST_VIEW],
    },
    {
      field: 'zone',
      contentType: 'string',
      rowSelector: 'zone.name',
      rowEditSelector: 'zoneId',
      required: true,
      searchType: 'multiSelectSearch',
      searchSelector: 'zoneId',
      editType: 'selectSearch',
      filterType: 'array',
      options: [],
      optionsValue: 'zoneId',
      defaultValue: 'peninsula',
    },
    {
      field: 'tariff',
      contentType: 'string',
      rowSelector: 'tariff.name',
      rowEditSelector: 'tariffId',
      required: true,
      searchType: 'multiSelectSearch',
      searchSelector: 'tariffId',
      editType: 'selectSearch',
      filterType: 'array',
      options: [],
      optionsValue: 'tariffId',
      defaultValue: '3.0TD',
    },
    {
      field: 'billingType',
      contentType: 'string',
      rowSelector: 'billingType.name',
      rowEditSelector: 'billingTypeId',
      required: true,
      searchType: 'multiSelectSearch',
      searchSelector: 'billingTypeId',
      editType: 'selectSearch',
      filterType: 'array',
      options: [],
      optionsValue: 'billingTypeId',
      defaultValue: 'indexada',
    },
    {
      field: 'distributor',
      contentType: 'string',
      rowSelector: 'distributor.name',
      rowEditSelector: 'distributorId',
      required: true,
      searchType: 'multiSelectSearch',
      searchSelector: 'distributorId',
      editType: 'selectSearch',
      filterType: 'array',
      options: [],
      optionsValue: 'distributorId',
    },
    {
      field: 'seller',
      contentType: 'string',
      rowSelector: 'seller.name',
      rowEditSelector: 'sellerId',
      required: true,
      searchType: 'multiSelectSearch',
      searchSelector: 'sellerId',
      editType: 'selectSearch',
      filterType: 'array',
      options: [],
      optionsValue: 'sellerId',
    },
    {
      field: 'appliesFrom',
      contentType: 'date',
      rowSelector: 'fromDateUnixTs',
      rowEditSelector: 'fromDateUnixTs',
      required: true,
      hideSeconds: false,
      searchType: 'date',
      editType: 'date',
      filterType: 'string',
      filterRange: true,
      options: [],
      cssClass: 'w-auto',
    },
    {
      field: 'voltage',
      contentType: 'number',
      rowSelector: 'voltage',
      rowEditSelector: 'voltage',
      required: true,
      searchType: 'number',
      editType: 'number',
      searchSelector: 'voltage',
      filterType: 'double',
      options: [],
      defaultValue: 230,
    },
    {
      field: 'contractedPower',
      contentType: 'array',
      rowSelector: 'contractedPower',
      rowEditSelector: 'contractedPower',
      required: true,
      searchType: 'number',
      searchSelector: 'contractedPower',
      filterType: 'double',
      options: [],
      hidden: [ModeEnum.LIST_EDIT, ModeEnum.SINGLE_CREATE, ModeEnum.SINGLE_EDIT],
    },

  ],
  actions: [
    { type: ActionEnum.EDIT },
    { type: ActionEnum.DELETE },
  ],
  multiActions: [
    {
      icon: 'trash-outline',
      name: 'delete',
      type: MultiActionEnum.DELETE,
    },
  ],
  editActions: [
    { type: ActionEnum.CANCEL },
    { type: ActionEnum.DELETE },
  ],
};
