import {
  ActionEnum,
  ModeEnum,
  MultiActionEnum,
  Strategy,
} from '@concordia-nx-ionic/concordia-shared';

export const metersDataConfig: Strategy = {
  name: 'energy_meters',
  entity: 'meter',
  column: 4,
  columns: [
    {
      field: 'viewAsUser',
      contentType: 'string',
      filterType: 'int',
      addFilter: false,
      rowSelector: 'view_as_user_id',
      searchType: 'selectSearch',
      searchSelector: 'view_as_user_id',
      hidden: [ ModeEnum.LIST_VIEW, ModeEnum.LIST_EDIT, ModeEnum.SINGLE_CREATE, ModeEnum.SINGLE_EDIT],
      options: [],
      required: true,
      disabled: false,
      optionsField: 'name',
      optionsGroup: 'userLevelId',
      optionsValue: 'userId',
    },
    {
      field: 'creationDate',
      contentType: 'date',
      addFilter: true,
      rowSelector: 'created_at',
      searchType: 'date',
      editType: 'date',
      filterType: 'string',
      filterRange: true,
      hidden: [ ModeEnum.LIST_VIEW, ModeEnum.LIST_EDIT, ModeEnum.SINGLE_CREATE, ModeEnum.SINGLE_EDIT],
      options: [],
    },
    {
      field: 'name',
      contentType: 'string',
      fixed: true,
      filterType: 'string',
      rowSelector: 'name',
      searchType: 'text',
      required: true,
      options: [],
      link: {
        field: '_id',
        pref: '/energy/meters',
        sfx: '',
      },
    },
    {
      field: 'description',
      contentType: 'string',
      fixed: false,
      filterType: 'string',
      rowSelector: 'description',
      searchType: 'text',
      required: false,
      options: [],
    },
    {
      field: 'owner',
      contentType: 'string',
      filterType: 'int',
      rowSelector: 'owner.name',
      rowEditSelector: 'ownerId',
      searchType: 'selectSearch',
      searchSelector: 'ownerId',
      options: [],
      required: true,
      disabled: false,
      optionsField: 'name',
      optionsGroup: 'userLevelId',
      optionsValue: 'userId',
    },
    {
      field: 'public',
      contentType: 'switch',
      filterType: 'boolean',
      actions: [
        {
          value: true,
          icon: 'eye-outline',
          background: 'success',
          fill: 'solid',
          color: 'light',
          name: 'table.makePrivate',
          type: ActionEnum.DEACTIVATE,
        },
        {
          value: false,
          icon: 'eye-off-outline',
          background: 'light',
          fill: 'solid',
          color: 'dark',
          name: 'table.makePublic',
          type: ActionEnum.ACTIVATE,
        },
      ],
      rowSelector: 'isPublic',
      searchType: 'select',
      editType: 'switch',
      required: true,
      defaultValue: false,
      options: [
        { name: 'yes', _id: true },
        { name: 'no', _id: false },
      ],
      optionsTranslate: true,
    },
    {
      field: 'type',
      disabled: false,
      contentType: 'string',
      fixed: false,
      filterType: 'string',
      rowSelector: 'meterType',
      searchType: 'select',
      required: true,
      options: [
        { name: 'Electricity', _id: 'electricity' },
        { name: 'Heat', _id: 'heat' },
      ],
    },
    {
      field: 'country',
      disabled: true,
      contentType: 'string',
      fixed: false,
      filterType: 'string',
      rowSelector: 'country',
      searchType: 'select',
      required: true,
      options: [
        { name: 'Peru', _id: 'peru', hidden: false },
        { name: 'Spain', _id: 'spain', hidden: false },
        { name: 'Lithuania', _id: 'lithuania', hidden: true },
      ],
    },
    {
      field: 'ref',
      contentType: 'string',
      fixed: false,
      filterType: 'string',
      rowSelector: 'ref',
      searchType: 'text',
      required: false,
      options: [],
      hidden: [ ModeEnum.LIST_VIEW, ModeEnum.LIST_EDIT],
    },
    {
      field: 'timezone',
      contentType: 'string',
      rowSelector: 'timezone.shortName',
      rowEditSelector: 'timezoneId',
      required: true,
      searchType: 'selectSearch',
      searchSelector: 'timezoneId',
      editType: 'selectSearch',
      filterType: 'int',
      optionsField: 'name',
      optionsValue: 'timezoneId',
      options: [],
    },
    {
      field: 'address',
      contentType: 'string',
      fixed: false,
      colspan: 2,
      filterType: 'string',
      rowSelector: 'localization.address',
      searchType: 'text',
      required: false,
      options: [],
      hidden: [ ModeEnum.LIST_VIEW, ModeEnum.LIST_EDIT],
    },
    {
      field: 'latitude',
      contentType: 'number',
      fixed: false,
      filterType: 'string',
      rowSelector: 'localization.latitude',
      searchType: 'text',
      required: false,
      min: -90,
      max: 90,
      step: 0.000001,
      options: [],
      hidden: [ ModeEnum.LIST_VIEW, ModeEnum.LIST_EDIT],
    },
    {
      field: 'longitude',
      contentType: 'number',
      fixed: false,
      filterType: 'string',
      rowSelector: 'localization.longitude',
      searchType: 'text',
      required: false,
      min: -180,
      max: 180,
      step: 0.000001,
      options: [],
      hidden: [ ModeEnum.LIST_VIEW, ModeEnum.LIST_EDIT],
    },
    {
      field: 'client',
      contentType: 'string',
      filterType: 'int',
      colspan: 2,
      addFilter: false,
      rowSelector: 'clientId',
      rowEditSelector: 'clientId',
      searchType: 'select',
      hidden: [ ModeEnum.LIST_VIEW, ModeEnum.LIST_EDIT],
      options: [],
      required: false,
      disabled: false,
      optionsField: 'name',
      optionsValue: 'relationUserId',
    },
  ],
  actions: [
    { type: ActionEnum.EDIT },
    { type: ActionEnum.DELETE },
  ],
  multiActions: [
    {
      icon: 'eye-outline',
      name: 'makePublic',
      type: MultiActionEnum.ACTIVATE,
    },
    {
      icon: 'eye-off-outline',
      name: 'makePrivate',
      type: MultiActionEnum.DEACTIVATE,
    },
    {
      icon: 'trash-outline',
      name: 'delete',
      type: MultiActionEnum.DELETE,
    },
  ],
};
